language: python
  
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

before_install:
  - pip install pip --upgrade;
  - pip install -U pytest flake8;

install:
  - pip install -e .;

script:
  - flake8 altair_pandas;
  - python -m pytest --backend_name=altair altair_pandas;
